language: node_js

node_js:
  - 6
  - 8
  - 10

notifications:
  email:
    - lilleman@larvit.se

install:
  - npm i

before_script:
  - mysql -e 'CREATE DATABASE test'

script: DBCONFFILE=db_travis.json mocha

addons:
  mariadb: 10.3