
SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

CREATE TABLE `geo_counties` (
  `iso_3166_1_alpha_3` varchar(3) CHARACTER SET ascii NOT NULL,
  `label` varchar(193) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(5) COLLATE utf8mb4_unicode_ci NULL,
  PRIMARY KEY (`iso_3166_1_alpha_3`,`label`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `geo_municipalities` (
  `iso_3166_1_alpha_3` varchar(3) CHARACTER SET ascii NOT NULL,
  `county_label` varchar(193) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(193) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(5) COLLATE utf8mb4_unicode_ci NULL,
  PRIMARY KEY (`iso_3166_1_alpha_3`,`county_label`,`label`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `geo_counties` (`iso_3166_1_alpha_3`, `label`, `code`) VALUES
('SWE',	'Blekinge län',	'10'),
('SWE',	'Dalarnas län',	'20'),
('SWE',	'Gävleborgs län',	'21'),
('SWE',	'Gotlands län',	'09'),
('SWE',	'Hallands län',	'13'),
('SWE',	'Jämtlands län',	'23'),
('SWE',	'Jönköpings län',	'06'),
('SWE',	'Kalmar län',	'08'),
('SWE',	'Kronobergs län',	'07'),
('SWE',	'Norrbottens län',	'25'),
('SWE',	'Örebro län',	'18'),
('SWE',	'Östergötlands län',	'05'),
('SWE',	'Skåne län',	'12'),
('SWE',	'Södermanlands län',	'04'),
('SWE',	'Stockholms län',	'01'),
('SWE',	'Uppsala län',	'03'),
('SWE',	'Värmlands län',	'17'),
('SWE',	'Västerbottens län',	'24'),
('SWE',	'Västernorrlands län',	'22'),
('SWE',	'Västmanlands län',	'19'),
('SWE',	'Västra Götalands län',	'14');

INSERT INTO `geo_municipalities` (`iso_3166_1_alpha_3`, `county_label`, `label`, `code`) VALUES
('SWE',	'Blekinge län',	'Karlshamn',	'1082'),
('SWE',	'Blekinge län',	'Karlskrona',	'1080'),
('SWE',	'Blekinge län',	'Olofström',	'1060'),
('SWE',	'Blekinge län',	'Ronneby',	'1081'),
('SWE',	'Blekinge län',	'Sölvesborg',	'1083'),
('SWE',	'Dalarnas län',	'Älvdalen',	'2039'),
('SWE',	'Dalarnas län',	'Avesta',	'2084'),
('SWE',	'Dalarnas län',	'Borlänge',	'2081'),
('SWE',	'Dalarnas län',	'Falun',	'2080'),
('SWE',	'Dalarnas län',	'Gagnef',	'2026'),
('SWE',	'Dalarnas län',	'Hedemora',	'2083'),
('SWE',	'Dalarnas län',	'Leksand',	'2029'),
('SWE',	'Dalarnas län',	'Ludvika',	'2085'),
('SWE',	'Dalarnas län',	'Malung-Sälen',	'2023'),
('SWE',	'Dalarnas län',	'Mora',	'2062'),
('SWE',	'Dalarnas län',	'Orsa',	'2034'),
('SWE',	'Dalarnas län',	'Rättvik',	'2031'),
('SWE',	'Dalarnas län',	'Säter',	'2082'),
('SWE',	'Dalarnas län',	'Smedjebacken',	'2061'),
('SWE',	'Dalarnas län',	'Vansbro',	'2021'),
('SWE',	'Gävleborgs län',	'Bollnäs',	'2183'),
('SWE',	'Gävleborgs län',	'Gävle',	'2180'),
('SWE',	'Gävleborgs län',	'Hofors',	'2104'),
('SWE',	'Gävleborgs län',	'Hudiksvall',	'2184'),
('SWE',	'Gävleborgs län',	'Ljusdal',	'2161'),
('SWE',	'Gävleborgs län',	'Nordanstig',	'2132'),
('SWE',	'Gävleborgs län',	'Ockelbo',	'2101'),
('SWE',	'Gävleborgs län',	'Ovanåker',	'2121'),
('SWE',	'Gävleborgs län',	'Sandviken',	'2181'),
('SWE',	'Gävleborgs län',	'Söderhamn',	'2182'),
('SWE',	'Gotlands län',	'Gotland',	'0980'),
('SWE',	'Hallands län',	'Falkenberg',	'1382'),
('SWE',	'Hallands län',	'Halmstad',	'1380'),
('SWE',	'Hallands län',	'Hylte',	'1315'),
('SWE',	'Hallands län',	'Kungsbacka',	'1384'),
('SWE',	'Hallands län',	'Laholm',	'1381'),
('SWE',	'Hallands län',	'Varberg',	'1383'),
('SWE',	'Jämtlands län',	'Åre',	'2321'),
('SWE',	'Jämtlands län',	'Berg',	'2326'),
('SWE',	'Jämtlands län',	'Bräcke',	'2305'),
('SWE',	'Jämtlands län',	'Härjedalen',	'2361'),
('SWE',	'Jämtlands län',	'Krokom',	'2309'),
('SWE',	'Jämtlands län',	'Östersund',	'2380'),
('SWE',	'Jämtlands län',	'Ragunda',	'2303'),
('SWE',	'Jämtlands län',	'Strömsund',	'2313'),
('SWE',	'Jönköpings län',	'Aneby',	'0604'),
('SWE',	'Jönköpings län',	'Eksjö',	'0686'),
('SWE',	'Jönköpings län',	'Gislaved',	'0662'),
('SWE',	'Jönköpings län',	'Gnosjö',	'0617'),
('SWE',	'Jönköpings län',	'Habo',	'0643'),
('SWE',	'Jönköpings län',	'Jönköping',	'0680'),
('SWE',	'Jönköpings län',	'Mullsjö',	'0642'),
('SWE',	'Jönköpings län',	'Nässjö',	'0682'),
('SWE',	'Jönköpings län',	'Sävsjö',	'0684'),
('SWE',	'Jönköpings län',	'Tranås',	'0687'),
('SWE',	'Jönköpings län',	'Vaggeryd',	'0665'),
('SWE',	'Jönköpings län',	'Värnamo',	'0683'),
('SWE',	'Jönköpings län',	'Vetlanda',	'0685'),
('SWE',	'Kalmar län',	'Borgholm',	'0885'),
('SWE',	'Kalmar län',	'Emmaboda',	'0862'),
('SWE',	'Kalmar län',	'Högsby',	'0821'),
('SWE',	'Kalmar län',	'Hultsfred',	'0860'),
('SWE',	'Kalmar län',	'Kalmar',	'0880'),
('SWE',	'Kalmar län',	'Mönsterås',	'0861'),
('SWE',	'Kalmar län',	'Mörbylånga',	'0840'),
('SWE',	'Kalmar län',	'Nybro',	'0881'),
('SWE',	'Kalmar län',	'Oskarshamn',	'0882'),
('SWE',	'Kalmar län',	'Torsås',	'0834'),
('SWE',	'Kalmar län',	'Västervik',	'0883'),
('SWE',	'Kalmar län',	'Vimmerby',	'0884'),
('SWE',	'Kronobergs län',	'Älmhult',	'0765'),
('SWE',	'Kronobergs län',	'Alvesta',	'0764'),
('SWE',	'Kronobergs län',	'Lessebo',	'0761'),
('SWE',	'Kronobergs län',	'Ljungby',	'0781'),
('SWE',	'Kronobergs län',	'Markaryd',	'0767'),
('SWE',	'Kronobergs län',	'Tingsryd',	'0763'),
('SWE',	'Kronobergs län',	'Uppvidinge',	'0760'),
('SWE',	'Kronobergs län',	'Växjö',	'0780'),
('SWE',	'Norrbottens län',	'Älvsbyn',	'2560'),
('SWE',	'Norrbottens län',	'Arjeplog',	'2506'),
('SWE',	'Norrbottens län',	'Arvidsjaur',	'2505'),
('SWE',	'Norrbottens län',	'Boden',	'2582'),
('SWE',	'Norrbottens län',	'Gällivare',	'2523'),
('SWE',	'Norrbottens län',	'Haparanda',	'2583'),
('SWE',	'Norrbottens län',	'Jokkmokk',	'2510'),
('SWE',	'Norrbottens län',	'Kalix',	'2514'),
('SWE',	'Norrbottens län',	'Kiruna',	'2584'),
('SWE',	'Norrbottens län',	'Luleå',	'2580'),
('SWE',	'Norrbottens län',	'Överkalix',	'2513'),
('SWE',	'Norrbottens län',	'Övertorneå',	'2518'),
('SWE',	'Norrbottens län',	'Pajala',	'2521'),
('SWE',	'Norrbottens län',	'Piteå',	'2581'),
('SWE',	'Örebro län',	'Askersund',	'1882'),
('SWE',	'Örebro län',	'Degerfors',	'1862'),
('SWE',	'Örebro län',	'Hällefors',	'1863'),
('SWE',	'Örebro län',	'Hallsberg',	'1861'),
('SWE',	'Örebro län',	'Karlskoga',	'1883'),
('SWE',	'Örebro län',	'Kumla',	'1881'),
('SWE',	'Örebro län',	'Laxå',	'1860'),
('SWE',	'Örebro län',	'Lekeberg',	'1814'),
('SWE',	'Örebro län',	'Lindesberg',	'1885'),
('SWE',	'Örebro län',	'Ljusnarsberg',	'1864'),
('SWE',	'Örebro län',	'Nora',	'1884'),
('SWE',	'Örebro län',	'Örebro',	'1880'),
('SWE',	'Östergötlands län',	'Åtvidaberg',	'0561'),
('SWE',	'Östergötlands län',	'Boxholm',	'0560'),
('SWE',	'Östergötlands län',	'Finspång',	'0562'),
('SWE',	'Östergötlands län',	'Kinda',	'0513'),
('SWE',	'Östergötlands län',	'Linköping',	'0580'),
('SWE',	'Östergötlands län',	'Mjölby',	'0586'),
('SWE',	'Östergötlands län',	'Motala',	'0583'),
('SWE',	'Östergötlands län',	'Norrköping',	'0581'),
('SWE',	'Östergötlands län',	'Ödeshög',	'0509'),
('SWE',	'Östergötlands län',	'Söderköping',	'0582'),
('SWE',	'Östergötlands län',	'Vadstena',	'0584'),
('SWE',	'Östergötlands län',	'Valdemarsvik',	'0563'),
('SWE',	'Östergötlands län',	'Ydre',	'0512'),
('SWE',	'Skåne län',	'Ängelholm',	'1292'),
('SWE',	'Skåne län',	'Åstorp',	'1277'),
('SWE',	'Skåne län',	'Båstad',	'1278'),
('SWE',	'Skåne län',	'Bjuv',	'1260'),
('SWE',	'Skåne län',	'Bromölla',	'1272'),
('SWE',	'Skåne län',	'Burlöv',	'1231'),
('SWE',	'Skåne län',	'Eslöv',	'1285'),
('SWE',	'Skåne län',	'Hässleholm',	'1293'),
('SWE',	'Skåne län',	'Helsingborg',	'1283'),
('SWE',	'Skåne län',	'Höganäs',	'1284'),
('SWE',	'Skåne län',	'Höör',	'1267'),
('SWE',	'Skåne län',	'Hörby',	'1266'),
('SWE',	'Skåne län',	'Kävlinge',	'1261'),
('SWE',	'Skåne län',	'Klippan',	'1276'),
('SWE',	'Skåne län',	'Kristianstad',	'1290'),
('SWE',	'Skåne län',	'Landskrona',	'1282'),
('SWE',	'Skåne län',	'Lomma',	'1262'),
('SWE',	'Skåne län',	'Lund',	'1281'),
('SWE',	'Skåne län',	'Malmö',	'1280'),
('SWE',	'Skåne län',	'Örkelljunga',	'1257'),
('SWE',	'Skåne län',	'Osby',	'1273'),
('SWE',	'Skåne län',	'Östra Göinge',	'1256'),
('SWE',	'Skåne län',	'Perstorp',	'1275'),
('SWE',	'Skåne län',	'Simrishamn',	'1291'),
('SWE',	'Skåne län',	'Sjöbo',	'1265'),
('SWE',	'Skåne län',	'Skurup',	'1264'),
('SWE',	'Skåne län',	'Staffanstorp',	'1230'),
('SWE',	'Skåne län',	'Svalöv',	'1214'),
('SWE',	'Skåne län',	'Svedala',	'1263'),
('SWE',	'Skåne län',	'Tomelilla',	'1270'),
('SWE',	'Skåne län',	'Trelleborg',	'1287'),
('SWE',	'Skåne län',	'Vellinge',	'1233'),
('SWE',	'Skåne län',	'Ystad',	'1286'),
('SWE',	'Södermanlands län',	'Eskilstuna',	'0484'),
('SWE',	'Södermanlands län',	'Flen',	'0482'),
('SWE',	'Södermanlands län',	'Gnesta',	'0461'),
('SWE',	'Södermanlands län',	'Katrineholm',	'0483'),
('SWE',	'Södermanlands län',	'Nyköping',	'0480'),
('SWE',	'Södermanlands län',	'Oxelösund',	'0481'),
('SWE',	'Södermanlands län',	'Strängnäs',	'0486'),
('SWE',	'Södermanlands län',	'Trosa',	'0488'),
('SWE',	'Södermanlands län',	'Vingåker',	'0428'),
('SWE',	'Stockholms län',	'Botkyrka',	'0127'),
('SWE',	'Stockholms län',	'Danderyd',	'0162'),
('SWE',	'Stockholms län',	'Ekerö',	'0125'),
('SWE',	'Stockholms län',	'Haninge',	'0136'),
('SWE',	'Stockholms län',	'Huddinge',	'0126'),
('SWE',	'Stockholms län',	'Järfälla',	'0123'),
('SWE',	'Stockholms län',	'Lidingö',	'0186'),
('SWE',	'Stockholms län',	'Nacka',	'0182'),
('SWE',	'Stockholms län',	'Norrtälje',	'0188'),
('SWE',	'Stockholms län',	'Nykvarn',	'0140'),
('SWE',	'Stockholms län',	'Nynäshamn',	'0192'),
('SWE',	'Stockholms län',	'Österåker',	'0117'),
('SWE',	'Stockholms län',	'Salem',	'0128'),
('SWE',	'Stockholms län',	'Sigtuna',	'0191'),
('SWE',	'Stockholms län',	'Södertälje',	'0181'),
('SWE',	'Stockholms län',	'Sollentuna',	'0163'),
('SWE',	'Stockholms län',	'Solna',	'0184'),
('SWE',	'Stockholms län',	'Stockholm',	'0180'),
('SWE',	'Stockholms län',	'Sundbyberg',	'0183'),
('SWE',	'Stockholms län',	'Täby',	'0160'),
('SWE',	'Stockholms län',	'Tyresö',	'0138'),
('SWE',	'Stockholms län',	'Upplands Väsby',	'0114'),
('SWE',	'Stockholms län',	'Upplands-Bro',	'0139'),
('SWE',	'Stockholms län',	'Vallentuna',	'0115'),
('SWE',	'Stockholms län',	'Värmdö',	'0120'),
('SWE',	'Stockholms län',	'Vaxholm',	'0187'),
('SWE',	'Uppsala län',	'Älvkarleby',	'0319'),
('SWE',	'Uppsala län',	'Enköping',	'0381'),
('SWE',	'Uppsala län',	'Håbo',	'0305'),
('SWE',	'Uppsala län',	'Heby',	'0331'),
('SWE',	'Uppsala län',	'Knivsta',	'0330'),
('SWE',	'Uppsala län',	'Östhammar',	'0382'),
('SWE',	'Uppsala län',	'Tierp',	'0360'),
('SWE',	'Uppsala län',	'Uppsala',	'0380'),
('SWE',	'Värmlands län',	'Årjäng',	'1765'),
('SWE',	'Värmlands län',	'Arvika',	'1784'),
('SWE',	'Värmlands län',	'Eda',	'1730'),
('SWE',	'Värmlands län',	'Filipstad',	'1782'),
('SWE',	'Värmlands län',	'Forshaga',	'1763'),
('SWE',	'Värmlands län',	'Grums',	'1764'),
('SWE',	'Värmlands län',	'Hagfors',	'1783'),
('SWE',	'Värmlands län',	'Hammarö',	'1761'),
('SWE',	'Värmlands län',	'Karlstad',	'1780'),
('SWE',	'Värmlands län',	'Kil',	'1715'),
('SWE',	'Värmlands län',	'Kristinehamn',	'1781'),
('SWE',	'Värmlands län',	'Munkfors',	'1762'),
('SWE',	'Värmlands län',	'Säffle',	'1785'),
('SWE',	'Värmlands län',	'Storfors',	'1760'),
('SWE',	'Värmlands län',	'Sunne',	'1766'),
('SWE',	'Värmlands län',	'Torsby',	'1737'),
('SWE',	'Västerbottens län',	'Åsele',	'2463'),
('SWE',	'Västerbottens län',	'Bjurholm',	'2403'),
('SWE',	'Västerbottens län',	'Dorotea',	'2425'),
('SWE',	'Västerbottens län',	'Lycksele',	'2481'),
('SWE',	'Västerbottens län',	'Malå',	'2418'),
('SWE',	'Västerbottens län',	'Nordmaling',	'2401'),
('SWE',	'Västerbottens län',	'Norsjö',	'2417'),
('SWE',	'Västerbottens län',	'Robertsfors',	'2409'),
('SWE',	'Västerbottens län',	'Skellefteå',	'2482'),
('SWE',	'Västerbottens län',	'Sorsele',	'2422'),
('SWE',	'Västerbottens län',	'Storuman',	'2421'),
('SWE',	'Västerbottens län',	'Umeå',	'2480'),
('SWE',	'Västerbottens län',	'Vännäs',	'2460'),
('SWE',	'Västerbottens län',	'Vilhelmina',	'2462'),
('SWE',	'Västerbottens län',	'Vindeln',	'2404'),
('SWE',	'Västernorrlands län',	'Ånge',	'2260'),
('SWE',	'Västernorrlands län',	'Härnösand',	'2280'),
('SWE',	'Västernorrlands län',	'Kramfors',	'2282'),
('SWE',	'Västernorrlands län',	'Örnsköldsvik',	'2284'),
('SWE',	'Västernorrlands län',	'Sollefteå',	'2283'),
('SWE',	'Västernorrlands län',	'Sundsvall',	'2281'),
('SWE',	'Västernorrlands län',	'Timrå',	'2262'),
('SWE',	'Västmanlands län',	'Arboga',	'1984'),
('SWE',	'Västmanlands län',	'Fagersta',	'1982'),
('SWE',	'Västmanlands län',	'Hallstahammar',	'1961'),
('SWE',	'Västmanlands län',	'Köping',	'1983'),
('SWE',	'Västmanlands län',	'Kungsör',	'1960'),
('SWE',	'Västmanlands län',	'Norberg',	'1962'),
('SWE',	'Västmanlands län',	'Sala',	'1981'),
('SWE',	'Västmanlands län',	'Skinnskatteberg',	'1904'),
('SWE',	'Västmanlands län',	'Surahammar',	'1907'),
('SWE',	'Västmanlands län',	'Västerås',	'1980'),
('SWE',	'Västra Götalands län',	'Ale',	'1440'),
('SWE',	'Västra Götalands län',	'Alingsås',	'1489'),
('SWE',	'Västra Götalands län',	'Åmål',	'1492'),
('SWE',	'Västra Götalands län',	'Bengtsfors',	'1460'),
('SWE',	'Västra Götalands län',	'Bollebygd',	'1443'),
('SWE',	'Västra Götalands län',	'Borås',	'1490'),
('SWE',	'Västra Götalands län',	'Dals-Ed',	'1438'),
('SWE',	'Västra Götalands län',	'Essunga',	'1445'),
('SWE',	'Västra Götalands län',	'Falköping',	'1499'),
('SWE',	'Västra Götalands län',	'Färgelanda',	'1439'),
('SWE',	'Västra Götalands län',	'Göteborg',	'1480'),
('SWE',	'Västra Götalands län',	'Götene',	'1471'),
('SWE',	'Västra Götalands län',	'Grästorp',	'1444'),
('SWE',	'Västra Götalands län',	'Gullspång',	'1447'),
('SWE',	'Västra Götalands län',	'Härryda',	'1401'),
('SWE',	'Västra Götalands län',	'Herrljunga',	'1466'),
('SWE',	'Västra Götalands län',	'Hjo',	'1497'),
('SWE',	'Västra Götalands län',	'Karlsborg',	'1446'),
('SWE',	'Västra Götalands län',	'Kungälv',	'1482'),
('SWE',	'Västra Götalands län',	'Lerum',	'1441'),
('SWE',	'Västra Götalands län',	'Lidköping',	'1494'),
('SWE',	'Västra Götalands län',	'Lilla Edet',	'1462'),
('SWE',	'Västra Götalands län',	'Lysekil',	'1484'),
('SWE',	'Västra Götalands län',	'Mariestad',	'1493'),
('SWE',	'Västra Götalands län',	'Mark',	'1463'),
('SWE',	'Västra Götalands län',	'Mellerud',	'1461'),
('SWE',	'Västra Götalands län',	'Mölndal',	'1481'),
('SWE',	'Västra Götalands län',	'Munkedal',	'1430'),
('SWE',	'Västra Götalands län',	'Öckerö',	'1407'),
('SWE',	'Västra Götalands län',	'Orust',	'1421'),
('SWE',	'Västra Götalands län',	'Partille',	'1402'),
('SWE',	'Västra Götalands län',	'Skara',	'1495'),
('SWE',	'Västra Götalands län',	'Skövde',	'1496'),
('SWE',	'Västra Götalands län',	'Sotenäs',	'1427'),
('SWE',	'Västra Götalands län',	'Stenungsund',	'1415'),
('SWE',	'Västra Götalands län',	'Strömstad',	'1486'),
('SWE',	'Västra Götalands län',	'Svenljunga',	'1465'),
('SWE',	'Västra Götalands län',	'Tanum',	'1435'),
('SWE',	'Västra Götalands län',	'Tibro',	'1472'),
('SWE',	'Västra Götalands län',	'Tidaholm',	'1498'),
('SWE',	'Västra Götalands län',	'Tjörn',	'1419'),
('SWE',	'Västra Götalands län',	'Töreboda',	'1473'),
('SWE',	'Västra Götalands län',	'Tranemo',	'1452'),
('SWE',	'Västra Götalands län',	'Trollhättan',	'1488'),
('SWE',	'Västra Götalands län',	'Uddevalla',	'1485'),
('SWE',	'Västra Götalands län',	'Ulricehamn',	'1491'),
('SWE',	'Västra Götalands län',	'Vänersborg',	'1487'),
('SWE',	'Västra Götalands län',	'Vara',	'1470'),
('SWE',	'Västra Götalands län',	'Vårgårda',	'1442');