ALTER TABLE `geo_regions` ADD `slug` varchar(50) COLLATE 'ascii_general_ci' NOT NULL, ADD `type` varchar(50) COLLATE 'ascii_general_ci' NOT NULL AFTER `slug`;
ALTER TABLE `geo_territories` ADD `slug` varchar(50) COLLATE 'ascii_general_ci' NOT NULL;
INSERT INTO geo_regions (id, name, slug, type) VALUES(999, 'Antarctica', 'antarctica', 'continent');
INSERT INTO geo_regions (id, name, slug, type) VALUES(1000, 'Southern America', 'southern-america', 'subcontinent');

UPDATE geo_regions SET slug = 'world', type = 'world' WHERE id = 1;
UPDATE geo_regions SET slug = 'africa', type = 'continent' WHERE id = 2;
UPDATE geo_regions SET slug = 'north-america', type = 'continent' WHERE id = 3;
UPDATE geo_regions SET slug = 'south-america', type = 'continent' WHERE id = 5;
UPDATE geo_regions SET slug = 'oceania', type = 'continent' WHERE id = 9;
UPDATE geo_regions SET slug = 'western-africa', type = 'subcontinent' WHERE id = 11;
UPDATE geo_regions SET slug = 'central-america', type = 'subcontinent' WHERE id = 13;
UPDATE geo_regions SET slug = 'eastern-africa', type = 'subcontinent' WHERE id = 14;
UPDATE geo_regions SET slug = 'northern-africa', type = 'subcontinent' WHERE id = 15;
UPDATE geo_regions SET slug = 'middle-africa', type = 'subcontinent' WHERE id = 17;
UPDATE geo_regions SET slug = 'southern-africa', type = 'subcontinent' WHERE id = 18;
UPDATE geo_regions SET slug = 'americas', type = 'hemisphere' WHERE id = 19;
UPDATE geo_regions SET slug = 'northern-america', type = 'subcontinent' WHERE id = 21;
UPDATE geo_regions SET slug = 'caribbean', type = 'subcontinent' WHERE id = 29;
UPDATE geo_regions SET slug = 'eastern-asia', type = 'subcontinent' WHERE id = 30;
UPDATE geo_regions SET slug = 'southern-asia', type = 'subcontinent' WHERE id = 34;
UPDATE geo_regions SET slug = 'southeast-asia', type = 'subcontinent' WHERE id = 35;
UPDATE geo_regions SET slug = 'southern-europe', type = 'subcontinent' WHERE id = 39;
UPDATE geo_regions SET slug = 'australasia', type = 'subcontinent' WHERE id = 53;
UPDATE geo_regions SET slug = 'melanesia', type = 'subcontinent' WHERE id = 54;
UPDATE geo_regions SET slug = 'micronesian-region', type = 'subcontinent' WHERE id = 57;
UPDATE geo_regions SET slug = 'polynesia', type = 'subcontinent' WHERE id = 61;
UPDATE geo_regions SET slug = 'asia', type = 'continent' WHERE id = 142;
UPDATE geo_regions SET slug = 'central-asia', type = 'subcontinent' WHERE id = 143;
UPDATE geo_regions SET slug = 'western-asia', type = 'subcontinent' WHERE id = 145;
UPDATE geo_regions SET slug = 'europe', type = 'continent' WHERE id = 150;
UPDATE geo_regions SET slug = 'eastern-europe', type = 'subcontinent' WHERE id = 151;
UPDATE geo_regions SET slug = 'northern-europe', type = 'subcontinent' WHERE id = 154;
UPDATE geo_regions SET slug = 'western-europe', type = 'subcontinent' WHERE id = 155;
UPDATE geo_regions SET slug = 'latin-america', type = 'subcontinent' WHERE id = 419;

INSERT INTO geo_regions_region (id, contains) VALUES(1,3),(1, 999),(1,5),(419,1000);

UPDATE geo_territories SET slug = 'afghanistan' WHERE iso3166_1_num = 4;
UPDATE geo_territories SET slug = 'albania' WHERE iso3166_1_num = 8;
UPDATE geo_territories SET slug = 'antarctica' WHERE iso3166_1_num = 10;
UPDATE geo_territories SET slug = 'algeria' WHERE iso3166_1_num = 12;
UPDATE geo_territories SET slug = 'american-samoa' WHERE iso3166_1_num = 16;
UPDATE geo_territories SET slug = 'andorra' WHERE iso3166_1_num = 20;
UPDATE geo_territories SET slug = 'angola' WHERE iso3166_1_num = 24;
UPDATE geo_territories SET slug = 'antigua-and-barbuda' WHERE iso3166_1_num = 28;
UPDATE geo_territories SET slug = 'azerbaijan' WHERE iso3166_1_num = 31;
UPDATE geo_territories SET slug = 'argentina' WHERE iso3166_1_num = 32;
UPDATE geo_territories SET slug = 'australia' WHERE iso3166_1_num = 36;
UPDATE geo_territories SET slug = 'austria' WHERE iso3166_1_num = 40;
UPDATE geo_territories SET slug = 'bahamas' WHERE iso3166_1_num = 44;
UPDATE geo_territories SET slug = 'bahrain' WHERE iso3166_1_num = 48;
UPDATE geo_territories SET slug = 'bangladesh' WHERE iso3166_1_num = 50;
UPDATE geo_territories SET slug = 'armenia' WHERE iso3166_1_num = 51;
UPDATE geo_territories SET slug = 'barbados' WHERE iso3166_1_num = 52;
UPDATE geo_territories SET slug = 'belgium' WHERE iso3166_1_num = 56;
UPDATE geo_territories SET slug = 'bermuda' WHERE iso3166_1_num = 60;
UPDATE geo_territories SET slug = 'bhutan' WHERE iso3166_1_num = 64;
UPDATE geo_territories SET slug = 'bolivia-plurinational-state-of' WHERE iso3166_1_num = 68;
UPDATE geo_territories SET slug = 'bosnia-and-herzegovina' WHERE iso3166_1_num = 70;
UPDATE geo_territories SET slug = 'botswana' WHERE iso3166_1_num = 72;
UPDATE geo_territories SET slug = 'bouvet-island' WHERE iso3166_1_num = 74;
UPDATE geo_territories SET slug = 'brazil' WHERE iso3166_1_num = 76;
UPDATE geo_territories SET slug = 'belize' WHERE iso3166_1_num = 84;
UPDATE geo_territories SET slug = 'british-indian-ocean-territory' WHERE iso3166_1_num = 86;
UPDATE geo_territories SET slug = 'solomon-islands' WHERE iso3166_1_num = 90;
UPDATE geo_territories SET slug = 'virgin-islands-british' WHERE iso3166_1_num = 92;
UPDATE geo_territories SET slug = 'brunei-darussalam' WHERE iso3166_1_num = 96;
UPDATE geo_territories SET slug = 'bulgaria' WHERE iso3166_1_num = 100;
UPDATE geo_territories SET slug = 'myanmar' WHERE iso3166_1_num = 104;
UPDATE geo_territories SET slug = 'burundi' WHERE iso3166_1_num = 108;
UPDATE geo_territories SET slug = 'belarus' WHERE iso3166_1_num = 112;
UPDATE geo_territories SET slug = 'cambodia' WHERE iso3166_1_num = 116;
UPDATE geo_territories SET slug = 'cameroon' WHERE iso3166_1_num = 120;
UPDATE geo_territories SET slug = 'canada' WHERE iso3166_1_num = 124;
UPDATE geo_territories SET slug = 'cabo-verde' WHERE iso3166_1_num = 132;
UPDATE geo_territories SET slug = 'cayman-islands' WHERE iso3166_1_num = 136;
UPDATE geo_territories SET slug = 'central-african-republic' WHERE iso3166_1_num = 140;
UPDATE geo_territories SET slug = 'sri-lanka' WHERE iso3166_1_num = 144;
UPDATE geo_territories SET slug = 'chad' WHERE iso3166_1_num = 148;
UPDATE geo_territories SET slug = 'chile' WHERE iso3166_1_num = 152;
UPDATE geo_territories SET slug = 'china' WHERE iso3166_1_num = 156;
UPDATE geo_territories SET slug = 'taiwan-province-of-china' WHERE iso3166_1_num = 158;
UPDATE geo_territories SET slug = 'christmas-island' WHERE iso3166_1_num = 162;
UPDATE geo_territories SET slug = 'cocos-keeling-islands' WHERE iso3166_1_num = 166;
UPDATE geo_territories SET slug = 'colombia' WHERE iso3166_1_num = 170;
UPDATE geo_territories SET slug = 'comoros' WHERE iso3166_1_num = 174;
UPDATE geo_territories SET slug = 'mayotte' WHERE iso3166_1_num = 175;
UPDATE geo_territories SET slug = 'congo' WHERE iso3166_1_num = 178;
UPDATE geo_territories SET slug = 'congo-democratic-republic-of-the' WHERE iso3166_1_num = 180;
UPDATE geo_territories SET slug = 'cook-islands' WHERE iso3166_1_num = 184;
UPDATE geo_territories SET slug = 'costa-rica' WHERE iso3166_1_num = 188;
UPDATE geo_territories SET slug = 'croatia' WHERE iso3166_1_num = 191;
UPDATE geo_territories SET slug = 'cuba' WHERE iso3166_1_num = 192;
UPDATE geo_territories SET slug = 'cyprus' WHERE iso3166_1_num = 196;
UPDATE geo_territories SET slug = 'czech-republic' WHERE iso3166_1_num = 203;
UPDATE geo_territories SET slug = 'benin' WHERE iso3166_1_num = 204;
UPDATE geo_territories SET slug = 'denmark' WHERE iso3166_1_num = 208;
UPDATE geo_territories SET slug = 'dominica' WHERE iso3166_1_num = 212;
UPDATE geo_territories SET slug = 'dominican-republic' WHERE iso3166_1_num = 214;
UPDATE geo_territories SET slug = 'ecuador' WHERE iso3166_1_num = 218;
UPDATE geo_territories SET slug = 'el-salvador' WHERE iso3166_1_num = 222;
UPDATE geo_territories SET slug = 'equatorial-guinea' WHERE iso3166_1_num = 226;
UPDATE geo_territories SET slug = 'ethiopia' WHERE iso3166_1_num = 231;
UPDATE geo_territories SET slug = 'eritrea' WHERE iso3166_1_num = 232;
UPDATE geo_territories SET slug = 'estonia' WHERE iso3166_1_num = 233;
UPDATE geo_territories SET slug = 'faroe-islands' WHERE iso3166_1_num = 234;
UPDATE geo_territories SET slug = 'falkland-islands-malvinas' WHERE iso3166_1_num = 238;
UPDATE geo_territories SET slug = 'south-georgia-and-the-south-sandwich-islands' WHERE iso3166_1_num = 239;
UPDATE geo_territories SET slug = 'fiji' WHERE iso3166_1_num = 242;
UPDATE geo_territories SET slug = 'finland' WHERE iso3166_1_num = 246;
UPDATE geo_territories SET slug = 'aland-islands' WHERE iso3166_1_num = 248;
UPDATE geo_territories SET slug = 'france' WHERE iso3166_1_num = 250;
UPDATE geo_territories SET slug = 'french-guiana' WHERE iso3166_1_num = 254;
UPDATE geo_territories SET slug = 'french-polynesia' WHERE iso3166_1_num = 258;
UPDATE geo_territories SET slug = 'french-southern-territories' WHERE iso3166_1_num = 260;
UPDATE geo_territories SET slug = 'djibouti' WHERE iso3166_1_num = 262;
UPDATE geo_territories SET slug = 'gabon' WHERE iso3166_1_num = 266;
UPDATE geo_territories SET slug = 'georgia' WHERE iso3166_1_num = 268;
UPDATE geo_territories SET slug = 'gambia' WHERE iso3166_1_num = 270;
UPDATE geo_territories SET slug = 'palestine-state-of' WHERE iso3166_1_num = 275;
UPDATE geo_territories SET slug = 'germany' WHERE iso3166_1_num = 276;
UPDATE geo_territories SET slug = 'ghana' WHERE iso3166_1_num = 288;
UPDATE geo_territories SET slug = 'gibraltar' WHERE iso3166_1_num = 292;
UPDATE geo_territories SET slug = 'kiribati' WHERE iso3166_1_num = 296;
UPDATE geo_territories SET slug = 'greece' WHERE iso3166_1_num = 300;
UPDATE geo_territories SET slug = 'greenland' WHERE iso3166_1_num = 304;
UPDATE geo_territories SET slug = 'grenada' WHERE iso3166_1_num = 308;
UPDATE geo_territories SET slug = 'guadeloupe' WHERE iso3166_1_num = 312;
UPDATE geo_territories SET slug = 'guam' WHERE iso3166_1_num = 316;
UPDATE geo_territories SET slug = 'guatemala' WHERE iso3166_1_num = 320;
UPDATE geo_territories SET slug = 'guinea' WHERE iso3166_1_num = 324;
UPDATE geo_territories SET slug = 'guyana' WHERE iso3166_1_num = 328;
UPDATE geo_territories SET slug = 'haiti' WHERE iso3166_1_num = 332;
UPDATE geo_territories SET slug = 'heard-island-and-mcdonald-islands' WHERE iso3166_1_num = 334;
UPDATE geo_territories SET slug = 'holy-see' WHERE iso3166_1_num = 336;
UPDATE geo_territories SET slug = 'honduras' WHERE iso3166_1_num = 340;
UPDATE geo_territories SET slug = 'hong-kong' WHERE iso3166_1_num = 344;
UPDATE geo_territories SET slug = 'hungary' WHERE iso3166_1_num = 348;
UPDATE geo_territories SET slug = 'iceland' WHERE iso3166_1_num = 352;
UPDATE geo_territories SET slug = 'india' WHERE iso3166_1_num = 356;
UPDATE geo_territories SET slug = 'indonesia' WHERE iso3166_1_num = 360;
UPDATE geo_territories SET slug = 'iran-islamic-republic-of' WHERE iso3166_1_num = 364;
UPDATE geo_territories SET slug = 'iraq' WHERE iso3166_1_num = 368;
UPDATE geo_territories SET slug = 'ireland' WHERE iso3166_1_num = 372;
UPDATE geo_territories SET slug = 'israel' WHERE iso3166_1_num = 376;
UPDATE geo_territories SET slug = 'italy' WHERE iso3166_1_num = 380;
UPDATE geo_territories SET slug = 'cote-divoire' WHERE iso3166_1_num = 384;
UPDATE geo_territories SET slug = 'jamaica' WHERE iso3166_1_num = 388;
UPDATE geo_territories SET slug = 'japan' WHERE iso3166_1_num = 392;
UPDATE geo_territories SET slug = 'kazakhstan' WHERE iso3166_1_num = 398;
UPDATE geo_territories SET slug = 'jordan' WHERE iso3166_1_num = 400;
UPDATE geo_territories SET slug = 'kenya' WHERE iso3166_1_num = 404;
UPDATE geo_territories SET slug = 'korea-democratic-peoples-republic-of' WHERE iso3166_1_num = 408;
UPDATE geo_territories SET slug = 'korea-republic-of' WHERE iso3166_1_num = 410;
UPDATE geo_territories SET slug = 'kuwait' WHERE iso3166_1_num = 414;
UPDATE geo_territories SET slug = 'kyrgyzstan' WHERE iso3166_1_num = 417;
UPDATE geo_territories SET slug = 'lao-peoples-democratic-republic' WHERE iso3166_1_num = 418;
UPDATE geo_territories SET slug = 'lebanon' WHERE iso3166_1_num = 422;
UPDATE geo_territories SET slug = 'lesotho' WHERE iso3166_1_num = 426;
UPDATE geo_territories SET slug = 'latvia' WHERE iso3166_1_num = 428;
UPDATE geo_territories SET slug = 'liberia' WHERE iso3166_1_num = 430;
UPDATE geo_territories SET slug = 'libya' WHERE iso3166_1_num = 434;
UPDATE geo_territories SET slug = 'liechtenstein' WHERE iso3166_1_num = 438;
UPDATE geo_territories SET slug = 'lithuania' WHERE iso3166_1_num = 440;
UPDATE geo_territories SET slug = 'luxembourg' WHERE iso3166_1_num = 442;
UPDATE geo_territories SET slug = 'macao' WHERE iso3166_1_num = 446;
UPDATE geo_territories SET slug = 'madagascar' WHERE iso3166_1_num = 450;
UPDATE geo_territories SET slug = 'malawi' WHERE iso3166_1_num = 454;
UPDATE geo_territories SET slug = 'malaysia' WHERE iso3166_1_num = 458;
UPDATE geo_territories SET slug = 'maldives' WHERE iso3166_1_num = 462;
UPDATE geo_territories SET slug = 'mali' WHERE iso3166_1_num = 466;
UPDATE geo_territories SET slug = 'malta' WHERE iso3166_1_num = 470;
UPDATE geo_territories SET slug = 'martinique' WHERE iso3166_1_num = 474;
UPDATE geo_territories SET slug = 'mauritania' WHERE iso3166_1_num = 478;
UPDATE geo_territories SET slug = 'mauritius' WHERE iso3166_1_num = 480;
UPDATE geo_territories SET slug = 'mexico' WHERE iso3166_1_num = 484;
UPDATE geo_territories SET slug = 'monaco' WHERE iso3166_1_num = 492;
UPDATE geo_territories SET slug = 'mongolia' WHERE iso3166_1_num = 496;
UPDATE geo_territories SET slug = 'moldova-republic-of' WHERE iso3166_1_num = 498;
UPDATE geo_territories SET slug = 'montenegro' WHERE iso3166_1_num = 499;
UPDATE geo_territories SET slug = 'montserrat' WHERE iso3166_1_num = 500;
UPDATE geo_territories SET slug = 'morocco' WHERE iso3166_1_num = 504;
UPDATE geo_territories SET slug = 'mozambique' WHERE iso3166_1_num = 508;
UPDATE geo_territories SET slug = 'oman' WHERE iso3166_1_num = 512;
UPDATE geo_territories SET slug = 'namibia' WHERE iso3166_1_num = 516;
UPDATE geo_territories SET slug = 'nauru' WHERE iso3166_1_num = 520;
UPDATE geo_territories SET slug = 'nepal' WHERE iso3166_1_num = 524;
UPDATE geo_territories SET slug = 'netherlands' WHERE iso3166_1_num = 528;
UPDATE geo_territories SET slug = 'curacao' WHERE iso3166_1_num = 531;
UPDATE geo_territories SET slug = 'aruba' WHERE iso3166_1_num = 533;
UPDATE geo_territories SET slug = 'sint-maarten-dutch-part' WHERE iso3166_1_num = 534;
UPDATE geo_territories SET slug = 'bonaire-sint-eustatius-and-saba' WHERE iso3166_1_num = 535;
UPDATE geo_territories SET slug = 'new-caledonia' WHERE iso3166_1_num = 540;
UPDATE geo_territories SET slug = 'vanuatu' WHERE iso3166_1_num = 548;
UPDATE geo_territories SET slug = 'new-zealand' WHERE iso3166_1_num = 554;
UPDATE geo_territories SET slug = 'nicaragua' WHERE iso3166_1_num = 558;
UPDATE geo_territories SET slug = 'niger' WHERE iso3166_1_num = 562;
UPDATE geo_territories SET slug = 'nigeria' WHERE iso3166_1_num = 566;
UPDATE geo_territories SET slug = 'niue' WHERE iso3166_1_num = 570;
UPDATE geo_territories SET slug = 'norfolk-island' WHERE iso3166_1_num = 574;
UPDATE geo_territories SET slug = 'norway' WHERE iso3166_1_num = 578;
UPDATE geo_territories SET slug = 'northern-mariana-islands' WHERE iso3166_1_num = 580;
UPDATE geo_territories SET slug = 'united-states-minor-outlying-islands' WHERE iso3166_1_num = 581;
UPDATE geo_territories SET slug = 'micronesia-federated-states-of' WHERE iso3166_1_num = 583;
UPDATE geo_territories SET slug = 'marshall-islands' WHERE iso3166_1_num = 584;
UPDATE geo_territories SET slug = 'palau' WHERE iso3166_1_num = 585;
UPDATE geo_territories SET slug = 'pakistan' WHERE iso3166_1_num = 586;
UPDATE geo_territories SET slug = 'panama' WHERE iso3166_1_num = 591;
UPDATE geo_territories SET slug = 'papua-new-guinea' WHERE iso3166_1_num = 598;
UPDATE geo_territories SET slug = 'paraguay' WHERE iso3166_1_num = 600;
UPDATE geo_territories SET slug = 'peru' WHERE iso3166_1_num = 604;
UPDATE geo_territories SET slug = 'philippines' WHERE iso3166_1_num = 608;
UPDATE geo_territories SET slug = 'pitcairn' WHERE iso3166_1_num = 612;
UPDATE geo_territories SET slug = 'poland' WHERE iso3166_1_num = 616;
UPDATE geo_territories SET slug = 'portugal' WHERE iso3166_1_num = 620;
UPDATE geo_territories SET slug = 'guinea-bissau' WHERE iso3166_1_num = 624;
UPDATE geo_territories SET slug = 'timor-leste' WHERE iso3166_1_num = 626;
UPDATE geo_territories SET slug = 'puerto-rico' WHERE iso3166_1_num = 630;
UPDATE geo_territories SET slug = 'qatar' WHERE iso3166_1_num = 634;
UPDATE geo_territories SET slug = 'reunion' WHERE iso3166_1_num = 638;
UPDATE geo_territories SET slug = 'romania' WHERE iso3166_1_num = 642;
UPDATE geo_territories SET slug = 'russian-federation' WHERE iso3166_1_num = 643;
UPDATE geo_territories SET slug = 'rwanda' WHERE iso3166_1_num = 646;
UPDATE geo_territories SET slug = 'saint-barthelemy' WHERE iso3166_1_num = 652;
UPDATE geo_territories SET slug = 'saint-helena-ascension-and-tristan-da-cunha' WHERE iso3166_1_num = 654;
UPDATE geo_territories SET slug = 'saint-kitts-and-nevis' WHERE iso3166_1_num = 659;
UPDATE geo_territories SET slug = 'anguilla' WHERE iso3166_1_num = 660;
UPDATE geo_territories SET slug = 'saint-lucia' WHERE iso3166_1_num = 662;
UPDATE geo_territories SET slug = 'saint-martin-french-part' WHERE iso3166_1_num = 663;
UPDATE geo_territories SET slug = 'saint-pierre-and-miquelon' WHERE iso3166_1_num = 666;
UPDATE geo_territories SET slug = 'saint-vincent-and-the-grenadines' WHERE iso3166_1_num = 670;
UPDATE geo_territories SET slug = 'san-marino' WHERE iso3166_1_num = 674;
UPDATE geo_territories SET slug = 'sao-tome-and-principe' WHERE iso3166_1_num = 678;
UPDATE geo_territories SET slug = 'saudi-arabia' WHERE iso3166_1_num = 682;
UPDATE geo_territories SET slug = 'senegal' WHERE iso3166_1_num = 686;
UPDATE geo_territories SET slug = 'serbia' WHERE iso3166_1_num = 688;
UPDATE geo_territories SET slug = 'seychelles' WHERE iso3166_1_num = 690;
UPDATE geo_territories SET slug = 'sierra-leone' WHERE iso3166_1_num = 694;
UPDATE geo_territories SET slug = 'singapore' WHERE iso3166_1_num = 702;
UPDATE geo_territories SET slug = 'slovakia' WHERE iso3166_1_num = 703;
UPDATE geo_territories SET slug = 'viet-nam' WHERE iso3166_1_num = 704;
UPDATE geo_territories SET slug = 'slovenia' WHERE iso3166_1_num = 705;
UPDATE geo_territories SET slug = 'somalia' WHERE iso3166_1_num = 706;
UPDATE geo_territories SET slug = 'south-africa' WHERE iso3166_1_num = 710;
UPDATE geo_territories SET slug = 'zimbabwe' WHERE iso3166_1_num = 716;
UPDATE geo_territories SET slug = 'spain' WHERE iso3166_1_num = 724;
UPDATE geo_territories SET slug = 'south-sudan' WHERE iso3166_1_num = 728;
UPDATE geo_territories SET slug = 'sudan' WHERE iso3166_1_num = 729;
UPDATE geo_territories SET slug = 'western-sahara' WHERE iso3166_1_num = 732;
UPDATE geo_territories SET slug = 'suriname' WHERE iso3166_1_num = 740;
UPDATE geo_territories SET slug = 'svalbard-and-jan-mayen' WHERE iso3166_1_num = 744;
UPDATE geo_territories SET slug = 'swaziland' WHERE iso3166_1_num = 748;
UPDATE geo_territories SET slug = 'sweden' WHERE iso3166_1_num = 752;
UPDATE geo_territories SET slug = 'switzerland' WHERE iso3166_1_num = 756;
UPDATE geo_territories SET slug = 'syrian-arab-republic' WHERE iso3166_1_num = 760;
UPDATE geo_territories SET slug = 'tajikistan' WHERE iso3166_1_num = 762;
UPDATE geo_territories SET slug = 'thailand' WHERE iso3166_1_num = 764;
UPDATE geo_territories SET slug = 'togo' WHERE iso3166_1_num = 768;
UPDATE geo_territories SET slug = 'tokelau' WHERE iso3166_1_num = 772;
UPDATE geo_territories SET slug = 'tonga' WHERE iso3166_1_num = 776;
UPDATE geo_territories SET slug = 'trinidad-and-tobago' WHERE iso3166_1_num = 780;
UPDATE geo_territories SET slug = 'united-arab-emirates' WHERE iso3166_1_num = 784;
UPDATE geo_territories SET slug = 'tunisia' WHERE iso3166_1_num = 788;
UPDATE geo_territories SET slug = 'turkey' WHERE iso3166_1_num = 792;
UPDATE geo_territories SET slug = 'turkmenistan' WHERE iso3166_1_num = 795;
UPDATE geo_territories SET slug = 'turks-and-caicos-islands' WHERE iso3166_1_num = 796;
UPDATE geo_territories SET slug = 'tuvalu' WHERE iso3166_1_num = 798;
UPDATE geo_territories SET slug = 'uganda' WHERE iso3166_1_num = 800;
UPDATE geo_territories SET slug = 'ukraine' WHERE iso3166_1_num = 804;
UPDATE geo_territories SET slug = 'macedonia-the-former-yugoslav-republic-of' WHERE iso3166_1_num = 807;
UPDATE geo_territories SET slug = 'egypt' WHERE iso3166_1_num = 818;
UPDATE geo_territories SET slug = 'united-kingdom-of-great-britain-and-northern-ireland' WHERE iso3166_1_num = 826;
UPDATE geo_territories SET slug = 'guernsey' WHERE iso3166_1_num = 831;
UPDATE geo_territories SET slug = 'jersey' WHERE iso3166_1_num = 832;
UPDATE geo_territories SET slug = 'isle-of-man' WHERE iso3166_1_num = 833;
UPDATE geo_territories SET slug = 'tanzania-united-republic-of' WHERE iso3166_1_num = 834;
UPDATE geo_territories SET slug = 'united-states-of-america' WHERE iso3166_1_num = 840;
UPDATE geo_territories SET slug = 'virgin-islands-us' WHERE iso3166_1_num = 850;
UPDATE geo_territories SET slug = 'burkina-faso' WHERE iso3166_1_num = 854;
UPDATE geo_territories SET slug = 'uruguay' WHERE iso3166_1_num = 858;
UPDATE geo_territories SET slug = 'uzbekistan' WHERE iso3166_1_num = 860;
UPDATE geo_territories SET slug = 'venezuela-bolivarian-republic-of' WHERE iso3166_1_num = 862;
UPDATE geo_territories SET slug = 'wallis-and-futuna' WHERE iso3166_1_num = 876;
UPDATE geo_territories SET slug = 'samoa' WHERE iso3166_1_num = 882;
UPDATE geo_territories SET slug = 'yemen' WHERE iso3166_1_num = 887;
UPDATE geo_territories SET slug = 'zambia' WHERE iso3166_1_num = 894;